name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Спеціальні дозволи, які потрібні GitHub Pages для розгортання сайту
permissions:
  contents: read
  pages: write
  id-token: write

# Запобігаємо тому, щоб два деплої одночасно перекривали один одного
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Тут буде посилання на твій сайт
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite за замовчуванням складає готовий сайт у папку 'dist'
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4